[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "time",
    "migrate",
]
