[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.79"
domain = { path = "../domain" }
paste = "1.0.14"
secrecy = { version = "0.8.0", features = ["alloc", "serde"] }
time = { version = "0.3.34", features = [
    "parsing",
    "formatting",
    "serde",
    "macros",
] }
use_cases = { path = "../use_cases" }
uuid = { version = "1.8.0", features = ["v4", "serde"] }

[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "time",
    "migrate",
]
