http_server:
  port: 80
  same_site: strict
  secure: true
database:
  connection_timeout_seconds: 3
redis:
  host: localhost
  port: 6379
password:
  hash_memory: 12288
  hash_iterations: 3
  hash_parallelism: 1
authorization:
  attempting_seconds: 300
  number_of_failures: 10
  access_token_seconds: 3600 # 1時間
  refresh_token_seconds: 259200 # 3日
logging:
  level: info
