[package]
name = "routes"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
mime = "0.3.17"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["std"] }
tracing = { version = "0.1.40", features = ["log"] }
